In [8]:
#import numpy module 
import numpy as np

In [9]:
# Creating the Numpy Array 
x = np.array([1,2,3,4,5,6],dtype=np.float32)

In [10]:
print(x)

[1. 2. 3. 4. 5. 6.]


In [11]:
# Size of Array 
np.size(x)

6

In [12]:
# Size of Array 
x.itemsize

4

In [16]:
# Creating a Sin Array 
y=np.sin(np.array([1,2,3,4,5],dtype=np.float32) )

In [17]:
print(y)

[ 0.84147096  0.9092974   0.14112    -0.7568025  -0.9589243 ]


In [19]:
from math import sin  #with math function
[sin(i) for i in [1,2,3]] 

[0.8414709848078965, 0.9092974268256817, 0.1411200080598672]

In [20]:
x=np.array([ [1,2,3],[4,5,6] ])
print(x)

[[1 2 3]
 [4 5 6]]


In [21]:
x.shape  # Shape of X

(2, 3)

In [23]:
x[0,:]  # Print 0th row and all columns  

array([1, 2, 3])

In [25]:
x[1,:] #  1st row

array([4, 5, 6])

In [28]:
# Creates a numpy array of Zero
x = np.ones((3,3))

In [30]:
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [37]:
x[:,[0,1,2,2]] # notice duplicated last dimension

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
 x[0,0]=999 # change element in x

In [39]:
x

array([[999.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [40]:
 x = np.arange(5) # create array

In [41]:
x

array([0, 1, 2, 3, 4])

In [42]:
y=x[[0,1,2]] # index by integer list to force copy

In [44]:
 from numpy.lib.stride_tricks import as_strided
 x = np.arange(16)
 y=as_strided(x,(7,4),(8,4)) # overlapped entries

In [45]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [46]:
y

array([[          0,  4294967296,           1,  8589934592],
       [          1,  8589934592,           2, 12884901888],
       [          2, 12884901888,           3, 17179869184],
       [          3, 17179869184,           4, 21474836480],
       [          4, 21474836480,           5, 25769803776],
       [          5, 25769803776,           6, 30064771072],
       [          6, 30064771072,           7, 34359738368]])

In [47]:
x[::2]=99 # assign every other value

In [48]:
x

array([99,  1, 99,  3, 99,  5, 99,  7, 99,  9, 99, 11, 99, 13, 99, 15])

In [49]:
 import numpy as np
 A=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
 x=np.matrix([[1],[0],[0]])

matrix([[1],
        [4],
        [7]])

In [50]:
 A*x

matrix([[1],
        [4],
        [7]])

In [53]:
 x=np.array(A.dot(x))

In [54]:
 X,Y=np.meshgrid(np.arange(2),np.arange(2))

In [55]:
X,Y

(array([[0, 1],
        [0, 1]]), array([[0, 0],
        [1, 1]]))

In [56]:
X+Y

array([[0, 1],
       [1, 2]])

In [57]:
X-Y

array([[ 0,  1],
       [-1,  0]])

In [58]:
X*Y

array([[0, 0],
       [0, 1]])

In [59]:
X/Y

/home/angicia/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/home/angicia/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, inf],
       [ 0.,  1.]])

In [61]:
from numpy import ma # import masked arrays
x = np.arange(10)
y = ma.masked_array(x, x<5)
print(y)

[-- -- -- -- -- 5 6 7 8 9]
