In [1]:
import tensorflow as tf

/home/angicia/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/angicia/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/angicia/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/angicia/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:5

In [2]:
x1 = tf.constant([1,2,3,4])

In [3]:
x1

<tf.Tensor 'Const:0' shape=(4,) dtype=int32>

In [4]:
print(x1)

Tensor("Const:0", shape=(4,), dtype=int32)


In [5]:
x2 = tf.constant([5,6,7,8])

In [6]:
x1*x2

<tf.Tensor 'mul:0' shape=(4,) dtype=int32>

In [7]:
sess = tf.Session()

In [8]:
print(sess.run(x1*x2))

[ 5 12 21 32]


In [9]:
sess.close()

In [10]:
import numpy as np

In [11]:
X_1 = tf.placeholder(tf.float32, name = "X_1")

In [12]:
X_2 = tf.placeholder(tf.float32, name = "X_2")

In [13]:
multiply = tf.multiply(X_1, X_2, name = "multiply")

In [14]:
with tf.Session() as session:
    result = session.run(multiply, feed_dict={X_1:[1,2,3], X_2:[4,5,6]})
    print(result)

[ 4. 10. 18.]


In [15]:
# Import `tensorflow`
import tensorflow as tf

# Initialize two constants
x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])

# Multiply
result = tf.multiply(x1, x2)

# Initialize Session and run `result`
with tf.Session() as sess:
  output = sess.run(result)
  print(output)

[ 5 12 21 32]


In [16]:
matrix1 = np.array([(2,2,2),(2,2,2),(2,2,2)],dtype = 'int32')
matrix2 = np.array([(1,1,1),(1,1,1),(1,1,1)],dtype = 'int32')

In [17]:
matrix1

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int32)

In [18]:
matrix2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [19]:
matrix1 = tf.constant(matrix1)
matrix2 = tf.constant(matrix2)

In [20]:
matrix_product = tf.matmul(matrix1, matrix2)

In [21]:
matrix_sum = tf.add(matrix1,matrix2)

In [22]:
matrix_3 = np.array([(2,7,2),(1,4,2),(9,0,2)],dtype = 'float32')

In [23]:
print(matrix_3)

[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]


In [24]:
matrix_det = tf.matrix_determinant(matrix_3)

In [25]:
with tf.Session() as sess:
   result1 = sess.run(matrix_product)
   result2 = sess.run(matrix_sum)
   result3 = sess.run(matrix_det)

In [26]:
print (result1)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [27]:
print (result2)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [28]:
print (result3)

55.999992


In [29]:
import tensorflow as tf
import numpy as np
from tensorflow.examples.tutorials.mnist import input_data

In [30]:
def run_cnn():
   mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)
   learning_rate = 0.0001
   epochs = 10
   batch_size = 50

In [31]:
x = tf.placeholder(tf.float32, [None, 784])

In [32]:
x_shaped = tf.reshape(x, [-1, 28, 28, 1])

In [33]:
y = tf.placeholder(tf.float32, [None, 10])

In [34]:
x = tf.constant(-2.0, name="i", dtype=tf.float32)
a = tf.constant(5.0, name="j", dtype=tf.float32)
b = tf.constant(13.0, name="k", dtype=tf.float32)

In [35]:
sess = tf.Session()
print(sess.run(x))

-2.0
