In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
datas = pd.read_csv('LinearData.csv')
datas

X      Y
0    1    953
1    2   2068
2    3   2871
3    4   3972
4    5   5240
5    6   5610
6    7   7196
7    8   7936
8    9   8577
9   10  10950
10  11  11077
11  12  12468
12  13  13780
13  14  13888
14  15  14325
15  16  14496
16  17  16116
17  18  17064
18  19  20387
19  20  18620
20  21  20517
21  22  22264
22  23  22770
23  24  25344
24  25  23450
25  26  28522
26  27  25920
27  28  30072
28  29  31813
29  30  32370

In [2]:
X = datas.iloc[:, :-1].values
y = datas.iloc[:, -1].values

In [3]:
X

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30]])

In [4]:
y

array([  953,  2068,  2871,  3972,  5240,  5610,  7196,  7936,  8577,
       10950, 11077, 12468, 13780, 13888, 14325, 14496, 16116, 17064,
       20387, 18620, 20517, 22264, 22770, 25344, 23450, 28522, 25920,
       30072, 31813, 32370])

In [5]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

In [6]:
X, y = make_regression(n_features=4, n_informative=2, random_state=0, shuffle=False)
clf = RandomForestRegressor(max_depth=2, random_state=0)
clf.fit(X, y)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=2, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [7]:
clf.predict(X)

array([ 29.61901976, -11.02118762,  14.62139516,   9.80192217,
         0.49423187,   6.4746029 , -20.32548943,  60.07190209,
       -43.63959083,  57.75151636, -42.08374658, -29.21899598,
       -26.87520041, -35.5562676 ,  13.00221212, -30.27667951,
       -15.30998867, -15.07085954, -14.3798838 , -32.77944477,
        17.75011607,  60.75235947,  32.39695083,  34.89481082,
        41.82746706, -15.81990323,  38.35651914,  61.7155606 ,
        39.8305456 ,   0.21346688, -18.52788719, -15.07085954,
        20.03487674, -15.07085954,  -2.64590913,   6.29322227,
        53.24909298, -31.72005631, -32.77944477, -11.61409181,
        39.8305456 ,  15.42240915,  20.19566646, -11.02118762,
       -32.77944477, -39.77817286, -27.75309607,  39.8305456 ,
       -29.94592506,  28.81337665, -27.04219045, -27.75309607,
        -2.98099169, -10.23166651,  12.18025706, -30.52121188,
       -16.64428086, -27.76253299,  12.5021081 , -21.88133368,
       -29.93933852, -40.90011089, -43.63959083, -15.69